name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: odin version
  plugin_test_macos:
    runs-on: macos-latest
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: odin version
